name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "shirokane232@gmail.com"
          git config --global user.name "shirokane232"
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/shirokane232/shirokane.git

      - name: Run deploy:static Script
        run: npm run deploy:static
